namespace GEOWALL_E
{
    // Esta es la clase que le va a dar las propiedades al token
    enum Tipo_De_Token
    {
        //tokens
        Numero,
        String,
        Comillas,
        coma,
        Suma,
        Resta,
        Producto,
        Division,
        Potenciacion,
        Parentesis_Abierto,
        Parentesis_Cerrado,
        Bang,
        Igual,
        Implicacion,
        AmpersandAmpersand,
        PipePipe,
        Menor_que,
        Menor_igual_que,
        Mayor_que,
        Mayor_igual_que,
        IgualIgual,
        Bang_Igual,
        Espacio,
        Malo,
        punto_y_coma,
        Final,
        Identificador,
        Declaracion_Funcion,
        LLamada_Funcion,
        concatenacion,
        resto,
        salto_de_linea,
        la_nada,
        Corchete_Abierto,
        Corchete_Cerrado,
        intervalo_infinito,

        //Keywords
        if_Keyword,
        then_Keyword,
        else_Keyword,
        print_Keyword,
        let_Keyword,
        in_Keyword,
        sen_Keyword,
        cos_Keyword,
        PI_Keyword,
        function_Keyword,
        logaritmo_Keyword,
        clean_keyword,

        //Expresiones
        Parentesis,
        Expresion_Unaria,
        Expresion_Binaria,
        Literal,
        Variable,
        if_Expresion,
        else_Expresion,
        Print_Expresion,
        let_in_Expresion,
        let_Expresion,
        in_Expresion,
        sen_Expresion,
        cos_Expresion,
        function_Expresion,
        parametros_Expresion,
        logaritmo_Expresion,
        clean_Expresion,
        asignacion_Expresion,
        asignacion_secuencia_Expresion,

        //Geometria expresiones
        point_Expresion,
        circle_Expresion,
        arc_Expresion,
        line_Expresion,
        ray_Expresion,
        segment_Expresion,
        measure_Expresion,
        secuencia_Expresion,
        secuencia_infinita_Expresion,
        undefined_Expresion,
        randoms_Expresion,
        samples_Expresion,
        count_Expresion,
        intersect_Expresion,

        point_sequence_Expresion,
        line_sequence_Expresion,
        circle_sequence_Expresion,
        ray_sequence_Expresion,
        segment_sequence_Expresion,

        draw_Expresion,

        //Geometria keywords
        arc_Keyword,
        circle_Keyword,
        line_Keyword,
        measure_Keyword,
        point_Keyword,
        ray_Keyword,
        segment_Keyword,
        count_Keyword,
        undefined_Keyword,
        randoms_Keyword,
        samples_Keyword,
        sequence_Keyword,
        intersect_Keyword,

        draw_Keyword,


        //Colores
        color_Keyword,
        color_Expresion,

        restore_Keyword,
        restore_Expresion,
    }
}

